export const STOP_TYPING = "STOP_TYPING";
export const START_TYPING = "START_TYPING";
export const CALCULATE_STATS = "CALCULATE_STATS";
export const UPDATE_USER_INPUT = "UPDATE_USER_INPUT";
export const UPDATE_CURRENT_KEY = "UPDATE_CURRENT_KEY";
